### ISSUE TITLE
Cannot open document with URI: com.android.providers.downloads.documents .

### ISSUE THREAD

**Issue by sonathati** [miguelpruivo/plugins_flutter_file_picker#7]
Cannot open document with URI: com.android.providers.downloads.documents.
App crashes when attaching document of above URI with below error : 
```
I/FilePicker( 7038): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker( 7038): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker( 7038): URI:content://com.android.providers.downloads.documents/document/2350
E/FilePathPicker( 7038): +++ API 19 URI :: content://com.android.providers.downloads.documents/document/2350
E/FilePathPicker( 7038): +++ Document URI
E/FilePathPicker( 7038): +++ Downloads External Document URI
D/AndroidRuntime( 7038): Shutting down VM
E/AndroidRuntime( 7038): FATAL EXCEPTION: main
E/AndroidRuntime( 7038): Process: com.coromandel.ideaspace, PID: 7038
E/AndroidRuntime( 7038): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=43, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/2350 flg=0x43 }} to activity {com.coromandel.ideaspace/com.coromandel.ideaspace.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2350
E/AndroidRuntime( 7038): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4440)
E/AndroidRuntime( 7038): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)
E/AndroidRuntime( 7038): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime( 7038): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
E/AndroidRuntime( 7038): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7038): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 7038): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
E/AndroidRuntime( 7038): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7038): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
E/AndroidRuntime( 7038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime( 7038): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2350
E/AndroidRuntime( 7038): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime( 7038): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime( 7038): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:432)
E/AndroidRuntime( 7038): 	at android.content.ContentResolver.query(ContentResolver.java:793)
E/AndroidRuntime( 7038): 	at android.content.ContentResolver.query(ContentResolver.java:712)
E/AndroidRuntime( 7038): 	at android.content.ContentResolver.query(ContentResolver.java:670)
E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePath.getDataColumn(FilePath.java:121)
E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePath.getForApi19(FilePath.java:66)
E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePath.getPath(FilePath.java:26)
E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:49)
E/AndroidRuntime( 7038): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 7038): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 7038): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 7038): 	at android.app.Activity.dispatchActivityResult(Activity.java:7317)
E/AndroidRuntime( 7038): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4436)
E/AndroidRuntime( 7038): 	... 9 more
W/OPDiagnose( 7038): getService:OPDiagnoseService NULL
D/OSTracker( 7038): OS Event: crash
```

**Comment by miguelpruivo** [comment]
What's the source of the file?

**Comment by NukanTran** [comment]
same issue

**Comment by miguelpruivo** [comment]
@NukanTran what’s the path from the file you’re trying to load? Can you post your logs?

**Comment by NukanTran** [comment]
I/FilePicker( 6736): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker( 6736): URI:content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fa.pdf
E/FilePathPicker( 6736): +++ API 19 URI :: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fa.pdf
E/FilePathPicker( 6736): +++ Document URI
E/FilePathPicker( 6736): +++ Downloads External Document URI
D/AndroidRuntime( 6736): Shutting down VM
E/AndroidRuntime( 6736): FATAL EXCEPTION: main
E/AndroidRuntime( 6736): Process: com.example.mytest, PID: 6736
E/AndroidRuntime( 6736): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=43, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/a.pdf flg=0x43 }} to activity {com.example.mytest/com.example.mytest.MainActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/a.pdf"
E/AndroidRuntime( 6736): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
E/AndroidRuntime( 6736): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
E/AndroidRuntime( 6736): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime( 6736): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
E/AndroidRuntime( 6736): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 6736): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 6736): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime( 6736): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6736): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime( 6736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime( 6736): Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/a.pdf"
E/AndroidRuntime( 6736): 	at java.lang.Long.parseLong(Long.java:590)
E/AndroidRuntime( 6736): 	at java.lang.Long.valueOf(Long.java:804)
E/AndroidRuntime( 6736): 	at com.mr.flutter.plugin.filepicker.FilePath.getForApi19(FilePath.java:64)
E/AndroidRuntime( 6736): 	at com.mr.flutter.plugin.filepicker.FilePath.getPath(FilePath.java:26)
E/AndroidRuntime( 6736): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:49)
E/AndroidRuntime( 6736): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 6736): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 6736): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 6736): 	at android.app.Activity.dispatchActivityResult(Activity.java:7235)
E/AndroidRuntime( 6736): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
E/AndroidRuntime( 6736): 	... 9 more

this is my logs

**Comment by miguelpruivo** [comment]
@NukanTran Thank you. What’s the android version?

**Comment by NukanTran** [comment]
Android 8.0 in Genymoution

**Comment by miguelpruivo** [comment]
@NukanTran @sonathati apparently there are some files started with "raw" string that may lead to this issue on Android 8.0. Doesn't seem to happen on other version though.

I couldn't replicate the issue, however I'm PR a fix to the beta branch and maybe later today to a version 1.0 on the master. 

Let me know if it worked for you.

**Comment by sonathati** [comment]
@miguelpruivo I just tried 1.0.2 from pub and build fails

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':file_picker:debugCompileClasspath'.
> Failed to transform file 'flutter.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file /Users/miguelruivo/DevTools/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

Flutter version:
`Flutter (Channel beta, v0.11.9, on Mac OS X 10.13.6 17G3025, locale en-IN)`

**Comment by miguelpruivo** [comment]
@sonathati glad that you’ve spotted it. I know what it is, that’s something that shouldn’t had been committed. I’ll fix it later today.

**Comment by sonathati** [comment]
@miguelpruivo I am not able to get the file name when picked from *open from* view. But Iam able to retrieve the file name when attached from *file manager* available in the drawer
```
I/FilePicker( 9298): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker( 9298): URI:content://com.android.providers.downloads.documents/document/3023
E/FilePathPicker( 9298): +++ API 19 URI :: content://com.android.providers.downloads.documents/document/3023
E/FilePathPicker( 9298): +++ Document URI
E/FilePathPicker( 9298): +++ Downloads External Document URI
E/FilePathPicker( 9298): +++ Something went wrong while retrieving document path: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3023
I/FilePicker( 9298): Loaded file from cloud created on:/data/user/0/com.coromandel.ideaspace/cache/Document
I/FilePicker( 9298): Absolute file path:/data/user/0/com.coromandel.ideaspace/cache/Document
I/flutter ( 9298):  /data/user/0/com.coromandel.ideaspace/cache/Document
I/FilePicker( 9298): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker( 9298): URI:content://com.android.externalstorage.documents/document/primary%3ADownload%2F009E2D7C02DF488285C3409DC93A52D7.pdf
E/FilePathPicker( 9298): +++ API 19 URI :: content://com.android.externalstorage.documents/document/primary%3ADownload%2F009E2D7C02DF488285C3409DC93A52D7.pdf
E/FilePathPicker( 9298): +++ Document URI
E/FilePathPicker( 9298): +++ External Document URI
E/FilePathPicker( 9298): +++ Primary External Document URI
I/FilePicker( 9298): Absolute file path:/storage/emulated/0/Download/009E2D7C02DF488285C3409DC93A52D7.pdf
I/flutter ( 9298): /storage/emulated/0/Download/009E2D7C02DF488285C3409DC93A52D7.pdf
```

**Comment by miguelpruivo** [comment]
@sonathati I believe that is already fixed in the `beta` branch, could you give it a try? (You’ll need to add to your pubspec by using a git ref dependency).

**Comment by sonathati** [comment]
@miguelpruivo I have tried in beta branch by adding git ref dependency in my pubspec. But still not able to get the file name. Following are the logs

```
I/FilePicker(31444): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker(31444): Requesting permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker(31444): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker(31444): URI:content://com.android.providers.downloads.documents/document/3464
E/FilePathPicker(31444): +++ API 19 URI :: content://com.android.providers.downloads.documents/document/3464
E/FilePathPicker(31444): +++ Document URI
E/FilePathPicker(31444): +++ Downloads External Document URI
E/FilePathPicker(31444): +++ Something went wrong while retrieving document path: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3464
I/FilePicker(31444): Loaded file from cloud created on:/data/user/0/com.coromandel.ideaspace/cache/Document
I/FilePicker(31444): Absolute file path:/data/user/0/com.coromandel.ideaspace/cache/Document
I/flutter (31444): /data/user/0/com.coromandel.ideaspace/cache/Document
```

**Comment by miguelpruivo** [comment]
Hi again, this seems to be a very specific/tricky issue that might be related to the path of downloads folder or a disabled download manager. Anyway, I've committed an update that tries to solve or, at least, try to understand the issue. Could you clean & build with the `beta` again, to give it a try? 

Thank you.

**Comment by sonathati** [comment]
@miguelpruivo I could see issue still exists with the latest update, `beta` branch.
Issue is not seen for the same file attached from different view. Attaching the logs for both

Working case:
```
I/FilePicker(32236): URI:content://com.android.externalstorage.documents/document/primary%3ADownload%2FStoreList.pdf
E/FilePathPicker(32236): +++ API 19 URI :: content://com.android.externalstorage.documents/document/primary%3ADownload%2FStoreList.pdf
E/FilePathPicker(32236): +++ Document URI
E/FilePathPicker(32236): +++ External Document URI
E/FilePathPicker(32236): +++ Primary External Document URI
I/FilePicker(32236): Absolute file path:/storage/emulated/0/Download/StoreList.pdf
```

Not working case:
```
URI:content://com.android.providers.downloads.documents/document/3006
E/FilePathPicker(32236): +++ API 19 URI :: content://com.android.providers.downloads.documents/document/3006
E/FilePathPicker(32236): +++ Document URI
E/FilePathPicker(32236): +++ Downloads External Document URI
E/FilePathPicker(32236): +++ Something went wrong while retrieving document path: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3006
I/FilePicker(32236): Loaded file from cloud created on:/data/user/0/com.coromandel.ideaspace/cache/Document
I/FilePicker(32236): Absolute file path:/data/user/0/com.coromandel.ideaspace/cache/Document
```

**Comment by miguelpruivo** [comment]
Can I ask you where actually you’re trying to load the second path? I remember having an issue where some androids would display email attachments on the recent fails but the files weren’t actually there, it was like a placeholder.

**Comment by pushangupta** [comment]
@miguelpruivo I have noticed that this bug started from image_picker provide by flutter team. You are right about the disabled downloads manager. But one thing I noticed in your version was that file picker works great when the file type is set to any. But as soon as file type is set IMAGE, it fails and gives the fatal exception. I think when we fail to retrieve the file path, we must copy the file to the cache directory and then get the path from there. It seems you are already implementing this for documents but since you are using image_picker as the source for picking files, it fails.

**Comment by pushangupta** [comment]
@miguelpruivo FileType.IMAGE

**Comment by pushangupta** [comment]
@miguelpruivo Brother I did a little experiment. I changed the FileType to CUSTOM and gave file extension as JPG and guess what.. It fetched the exact same file it was failing on. Just a quick suggestion. If multiple file types(like JPG, PNG, SVG or JPEG) could be supported at the same time it would be better

**Comment by miguelpruivo** [comment]
@pushanguta that’s why it has the `FileType.IMAGE`, so it can filter all image file types at once, otherwise it wouldn’t make sense.

**Comment by pushangupta** [comment]
@miguelpruivo I mean, FileType.IMAGE surely uses image_picker... right? I am trying to avoid image_picker. Moreover if, for example, I wanted to select docs of extensions pdf, docx or ppt only what can I do?

**Comment by miguelpruivo** [comment]
@pushangupta right now you’d have to use `FileType.ALL` for that matter, but it’s a good suggestion that in a future update I add a `FileType.DOC` or so that will gather all of those file types in a filter at once.

**Comment by sonathati** [comment]
@miguelpruivo I had faced this issue with FileType.PDF
I have tried with file_picker: ^1.1.1 and its working fine for documents(using FileType.CUSTOM and fileExtension:'pdf') and for other FileTypes except for FileType.IMAGE.

For FileType.IMAGE my App crashes when trying to upload image, with following error:

```
D/AndroidRuntime(10073): Shutting down VM
E/AndroidRuntime(10073): FATAL EXCEPTION: main
E/AndroidRuntime(10073): Process: com.coromandel.ideaspace, PID: 10073
E/AndroidRuntime(10073): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/3411 flg=0x1 }} to activity {com.coromandel.ideaspace/com.coromandel.ideaspace.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3411
E/AndroidRuntime(10073): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4440)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(10073): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
E/AndroidRuntime(10073): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10073): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
E/AndroidRuntime(10073): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10073): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
E/AndroidRuntime(10073): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime(10073): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3411
E/AndroidRuntime(10073): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime(10073): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(10073): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:432)
E/AndroidRuntime(10073): 	at android.content.ContentResolver.query(ContentResolver.java:793)
E/AndroidRuntime(10073): 	at android.content.ContentResolver.query(ContentResolver.java:712)
E/AndroidRuntime(10073): 	at android.content.ContentResolver.query(ContentResolver.java:670)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:117)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:69)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(10073): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(10073): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(10073): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(10073): 	at android.app.Activity.dispatchActivityResult(Activity.java:7317)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4436)
E/AndroidRuntime(10073): 	... 9 more
W/OPDiagnose(10073): getService:OPDiagnoseService NULL
D/OSTracker(10073): OS Event: crash
```

**Comment by tiholic** [comment]
_info_: related issue from image_picker repo: https://github.com/flutter/flutter/issues/21863

**Comment by miguelpruivo** [comment]
@tiholic thank you for pointing it. It may be a possibility, I'll take a look when I have sometime, feel free to give it a try and PR if you find it fixing the problem while keeping all of the required features.

**Comment by tiholic** [comment]
Sure, I'll try and let you know

**Comment by tiholic** [comment]
It works great. I've tested for images, videos and pdf's.

https://github.com/miguelpruivo/plugins_flutter_file_picker/pull/26

**Comment by miguelpruivo** [comment]
@tiholic does it fixes this specific issue?

**Comment by miguelpruivo** [comment]
@tiholic does it fix this specific issue?

**Comment by tiholic** [comment]
Yes, now we can pick all types of files from downloads

**Comment by tiholic** [comment]
https://github.com/flutter/flutter/issues/21863

**Comment by Keng5594** [comment]
> Cannot open document with URI: com.android.providers.downloads.documents. App crashes when attaching document of above URI with below error :
> 
> ```
> I/FilePicker( 7038): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
> I/FilePicker( 7038): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
> I/FilePicker( 7038): URI:content://com.android.providers.downloads.documents/document/2350
> E/FilePathPicker( 7038): +++ API 19 URI :: content://com.android.providers.downloads.documents/document/2350
> E/FilePathPicker( 7038): +++ Document URI
> E/FilePathPicker( 7038): +++ Downloads External Document URI
> D/AndroidRuntime( 7038): Shutting down VM
> E/AndroidRuntime( 7038): FATAL EXCEPTION: main
> E/AndroidRuntime( 7038): Process: com.coromandel.ideaspace, PID: 7038
> E/AndroidRuntime( 7038): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=43, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/2350 flg=0x43 }} to activity {com.coromandel.ideaspace/com.coromandel.ideaspace.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2350
> E/AndroidRuntime( 7038): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4440)
> E/AndroidRuntime( 7038): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)
> E/AndroidRuntime( 7038): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
> E/AndroidRuntime( 7038): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
> E/AndroidRuntime( 7038): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime( 7038): 	at android.os.Looper.loop(Looper.java:164)
> E/AndroidRuntime( 7038): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
> E/AndroidRuntime( 7038): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 7038): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
> E/AndroidRuntime( 7038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> E/AndroidRuntime( 7038): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2350
> E/AndroidRuntime( 7038): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
> E/AndroidRuntime( 7038): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
> E/AndroidRuntime( 7038): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:432)
> E/AndroidRuntime( 7038): 	at android.content.ContentResolver.query(ContentResolver.java:793)
> E/AndroidRuntime( 7038): 	at android.content.ContentResolver.query(ContentResolver.java:712)
> E/AndroidRuntime( 7038): 	at android.content.ContentResolver.query(ContentResolver.java:670)
> E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePath.getDataColumn(FilePath.java:121)
> E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePath.getForApi19(FilePath.java:66)
> E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePath.getPath(FilePath.java:26)
> E/AndroidRuntime( 7038): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:49)
> E/AndroidRuntime( 7038): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
> E/AndroidRuntime( 7038): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
> E/AndroidRuntime( 7038): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
> E/AndroidRuntime( 7038): 	at android.app.Activity.dispatchActivityResult(Activity.java:7317)
> E/AndroidRuntime( 7038): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4436)
> E/AndroidRuntime( 7038): 	... 9 more
> W/OPDiagnose( 7038): getService:OPDiagnoseService NULL
> D/OSTracker( 7038): OS Event: crash
> ```
